@echo off
rem DFL-PT-WEBUI project-local environment. Preserve Windows user directories.
for %%D in ("%~dp0..") do set "DFL_PT_ROOT=%%~fD"
set "INTERNAL=%DFL_PT_ROOT%\_internal"
set "PYTHON_PATH=%DFL_PT_ROOT%\.venv\Scripts"
set "PYTHONHOME="
set "PYTHONPATH="
set "PYTHONNOUSERSITE=1"
set "PYTHON_EXECUTABLE=%PYTHON_PATH%\python.exe"
set "PYTHONEXECUTABLE=%PYTHON_EXECUTABLE%"
set "PYTHONW_EXECUTABLE=%PYTHON_PATH%\pythonw.exe"
set "PYTHONWEXECUTABLE=%PYTHONW_EXECUTABLE%"
set "PYTHON_BIN_PATH=%PYTHON_EXECUTABLE%"
set "PYTHON_LIB_PATH=%DFL_PT_ROOT%\.venv\Lib\site-packages"
set "NODE_BIN_PATH=%INTERNAL%\node\bin"
set "FFMPEG_PATH=%INTERNAL%\ffmpeg"
set "XNVIEWMP_PATH=%INTERNAL%\XnViewMP"
set "PATH=%PYTHON_PATH%;%NODE_BIN_PATH%;%FFMPEG_PATH%;%XNVIEWMP_PATH%;%PATH%"
set "WORKSPACE=%DFL_PT_ROOT%\workspace"
set "DFL_ROOT=%INTERNAL%\DeepFaceLab"
